### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by jonandersen** [alickbass/CodableFirebase#12]
Is there a way to support String or Int enums, or should we do that conversion manually? 

```swift
struct Model {
    let enumType: Int
    
    var actualEnumType : EnumType {
        return EnumType(enumType)
    }
}
```

**Comment by alickbass** [comment]
Hi @jonandersen ! Thanks for your question! You can use enums with `Codable`, you just need to make sure that your `EnumType` conforms to `Codable` protocol. Something like:

```swift
struct Model: Codable {
    enum EnumType: Int, Codable {
        case one, two, three
    }
    
    let enumType: EnumType
}
```

And then you can use it directly :)

**Comment by alickbass** [comment]
I have added an example with `enum` to the README

**Comment by jonandersen** [comment]
Thanks! That make total sense!
