### ISSUE TITLE
Decoding documentID

### ISSUE THREAD

**Issue by jonandersen** [alickbass/CodableFirebase#16]
What's the suggested way to decode the documentID? My current approach is something like this:

```swift
do {
   let partialTimeline = try FirestoreDecoder().decode(PartialTimeline.self, from: timeline.data())
    return partialTimeline.toTimeline(id: timeline.documentID)
} catch let error {
  recordError(error: error)
  return nil
}
```

**Comment by alickbass** [comment]
Hi @jonandersen! thanks for a question! Unfortunately timeline is not part of the `data()` dictionary. And because your `PartialTimeline` could potentially be used with other decoders, like `JSONDecoder` or `PlistDecoder`, I think your approach is the best workaround to this problem.

**Comment by alickbass** [comment]
If it's becoming a big issue, you could potentially write a protocol for models that expect `documentID`  and write your workaround in a reusable manner

**Comment by jonandersen** [comment]
@alickbass Thanks

**Comment by anelad** [comment]
This could be a easier approach

```
do {
    var timelineData = docSnapshot.data()
    timeline["uid"] = docSnaphot.documentId
    return try FirestoreDecoder().decode(Timeline.self, from: timelineData)
} catch let error {
  recordError(error: error)
  return nil
}
```
