### ISSUE TITLE
Issue with autoId

### ISSUE THREAD

**Issue by oniikal3** [alickbass/CodableFirebase#19]
Here's my model
AModel
- id: String
- myArray: [BModel]

BModel
- id: String
- x: String
- y: String

It's can't decode to [BModel] because type not match. It has to be [String:BModel]
String is a autoId that's create by Firebase 

How can I decode type from [String: BModel] to [BModel]

Do you have any suggestions

**Comment by alickbass** [comment]
Can you give me a `JSON` that you're trying to decode and Swift code that you are using?

**Comment by oniikal3** [comment]
Here's a structure

AChild
- UID
    - autoId
          - BChild
          - title
          - id

**Comment by oniikal3** [comment]
@alickbass 
What's your "container"?

**Comment by oniikal3** [comment]
@alickbass I already got it Thanks for your help. 👍

**Comment by alickbass** [comment]
Sure, no problem :) Don't forget to start the repo 😜

**Comment by denisoliveira** [comment]
@alickbass please add this solution as a sample on README.md I believe that some people have the same problem.
