### ISSUE TITLE
Issues with Decimal type

### ISSUE THREAD

**Issue by bumberboy** [alickbass/CodableFirebase#20]
Hi there! When I try to save Decimal types, I end up with this:
```
amount =             {
                exponent = 1;
                isCompact = 1;
                isNegative = 0;
                length = 1;
                mantissa =                 (
                    3,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0
                );
            };

```

Am I doing something wrong?

**Comment by bumberboy** [comment]
This is the FirestoreEncoder that I'm using.

**Comment by alickbass** [comment]
Hi @bumerboy! Thanks for reaching out! Can you provide me the code with your model so that I could check it out?

**Comment by bumberboy** [comment]
```
struct Expenditure: Codable {
    let amount: Decimal
    let categoryID: String
    let currency: String
}
```

Thanks for the response! Here it is.

**Comment by alickbass** [comment]
hey @bumberboy! I checked it and it seems that it is indeed a bug... I will check it out and let you know :)

**Comment by alickbass** [comment]
I have created a PR with the fix to this bug and now it should work fine :) Please let me know if it's gonna work for you
