### ISSUE TITLE
CodableFirebase issue for autoId handling

### ISSUE THREAD

**Issue by jibransiddiqui** [alickbass/CodableFirebase#23]
please tell me how can i use CodableFirebase for autoId Child like This 
{
...
"groups" : {
    "-L5d5ip5kOMe8m0ANHnC" : {
      "description" : "JS is iOS Developer Group",
      "duration" : 432000000,
      "name" : "JS Group",
      "ownerID" : "7oydaHRPmOYyrSS2IlJRlqYEw8J3",
      "state" : 1,
      "timestamp" : 1518960570194,
      "type" : 0
    },
    "-L5d6lX5lS2l33XFjBdI" : {
      "description" : "IOS Developer ",
      "duration" : 172800000,
      "name" : "iOS Dev",
      "ownerID" : "7oydaHRPmOYyrSS2IlJRlqYEw8J3",
      "state" : 0,
      "timestamp" : 1518960845938,
      "type" : 0
    }
  }
....
}

i want Codable for Group. 
please guide me.
please also find the attachment of DB Strcuture
<img width="464" alt="screen shot 2018-02-18 at 9 24 20 pm" src="https://user-images.githubusercontent.com/23705554/36354187-2bb8ee46-14f2-11e8-9dcd-b0450ee95df3.png">

**Comment by alickbass** [comment]
Hi @jibransiddiqui! Thanks for reaching out! There has already been a discussion to something similar to what you have [over here](https://github.com/alickbass/CodableFirebase/issues/19). Check it out and let me know if you find it helpful.

**Comment by alickbass** [comment]
It's been long time since this issue was updated, so I am gonna close it
