### ISSUE TITLE
How to parse array of dictionaries?

### ISSUE THREAD

**Issue by dterekhov** [alickbass/CodableFirebase#25]
```swift
let json = """
[
    {
        "name": "Banana",
        "points": 200,
        "description": "A banana grown in Ecuador."
    },
    {
        "name": "Orange",
        "points": 100
    }
]
"""

struct GroceryProduct: Codable {
    var name: String
    var points: Int
    var description: String?
}

let products = try FirebaseDecoder().decode([GroceryProduct].self, from: json)
```

Looks like `[GroceryProduct].self` doesn't work

**Comment by alickbass** [comment]
Hi @dterekhov!  Thanks for reaching out! `FirebaseDecoder` is supposed to be used with dictionaries, like `[String: Any]`. I think what you need to use is `JSONDecoder`. It will convert JSON string into array of codables.

Do something like"

```swift
let json = """
[
{
"name": "Banana",
"points": 200,
"description": "A banana grown in Ecuador."
},
{
"name": "Orange",
"points": 100
}
]
"""

let data = json.data(using: .utf8)!
let products = try! JSONDecoder().decode([GroceryProduct].self, from: data)
```

**Comment by dterekhov** [comment]
@alickbass Yes, it can be a workaround. But generally, I start to use this library because I want to avoid step on double conversation to Data -> MyModel.

**Comment by alickbass** [comment]
I would say like that: this library's purpose is to decode from / to dictionary in order to use it with Firebase Database and Firestore. What you are trying to parse (and correct me if I am wrong) is a JSON string, that is why I would say, that `JSONDecoder` is the perfect suite here. Converting `String` into `Data` is in my opinion, a necessary evil.

**Comment by tooolbox** [comment]
@alickbass Pardon me if this is a silly question, but how would I use FirebaseDecoder to decode an array from a Firebase data snapshot?

**Comment by tooolbox** [comment]
Nevermind, figured it out eventually from [this](https://stackoverflow.com/a/40251260/700471) and [this](https://stackoverflow.com/a/38269746/700471).  It would be cool if CodableFirebase was able to handle the scenario of a sorted array coming back from Firebase, like so:

```swift
db.child("blah").queryOrderedBy("myKey").observeSingleEvent(of: .value) { snapshot in
    do {
        let (keys, values) = try FirebaseDecoder().decodeArray([MyStruct].self, from: snapshot)
    } catch let error {
        print(error)
    }
}
```

**Comment by alickbass** [comment]
@tooolbox it already does that!

**Comment by alickbass** [comment]
Here's my data:
<img width="293" alt="screen shot 2018-02-27 at 21 27 24" src="https://user-images.githubusercontent.com/6421464/36753038-3518eca6-1c05-11e8-80bc-386fd6cc652c.png">

Here's the model:

```swift
struct Post: Codable {
    enum MyEnum: Int, Codable {
        case one, two, three
    }
    
    let author: String
    let body: String
    let enumVal: MyEnum
}
```

and here how you get it:

```swift
Firestore.firestore().collection("model").document("mc6wmez9OWo4Ny89UvPH").getDocument { (snapshot, error) in
    guard let snapshot = snapshot, let data = snapshot.data() else {
        print(error)
        return
    }
    do {
        let model = try FirestoreDecoder().decode(Model.self, from: data)
        print(model)
    } catch let decodingError {
        print(decodingError)
    }
}
```

**Comment by tooolbox** [comment]
Huh, yeah I see how that could work.  However, are you guaranteed to return it in sequence?

From my understanding, `value` is a Dictionary, which isn't enumerated sequentially in Swift.  That's why if you check out those posts I linked to, the recommended method is to do `for child in snapshot.children` to preserve the sequence, referencing `child.key` where necessary.

Here's how I'm doing it right now:

```swift
ref.child("blah").queryOrdered(byChild: "myKey").observeSingleEvent(of: .value) { (snapshot) in
    var resultArray: [MyStruct] = []
    for child in snapshot.children {
        guard let child = child as? DataSnapshot else { return }
        var myStruct: MyStruct
        do {
            myStruct = try FirebaseDecoder().decode(MyStruct.self, from: child)
        } catch let error {
            print("error")
        }
        myStruct.key = child.key
        resultArray.append(myStruct)
    }
}
```

The example syntax I gave with `decodeArray` could be some syntactic sugar for that.

**Comment by alickbass** [comment]
@tooolbox value is not a Dictionary. It can be `NSDictionary`, `NSArray`, `NSString`, `NSNumber`. So the order will be preserved, if it was saved as an Array before.

**Comment by alickbass** [comment]
Firebase Database returns `NSArray`, if you used `NSArray` to set the Data (meaning key is an integer). If not, then it's up to you to decide what to do with data.

**Comment by tooolbox** [comment]
Meaning if the key is a string, or if you're sorting by something other than the key before you return it, then you need to use `snapshot.children`.  I imagine this use case is not uncommon.

**Comment by alickbass** [comment]
And btw, your code can be written much shorter:

```swift
let result = try snapshot.children.flatMap({ ($0 as? DataSnapshot)?.value }).map({ try FirebaseDecoder().decode(MyStruct.self, from: $0) })
```

**Comment by alickbass** [comment]
Or you could do even better:

```swift
let value = try snapshot.children.flatMap({ ($0 as? DataSnapshot)?.value }) as Any
let result = try FirebaseDecoder().decode(MyStruct.self, from: value)
```

**Comment by tooolbox** [comment]
Nice, except you have to preserve the keys in the structs.
```swift
let (keys, values) = snapshot.children.reduce(into: ([String](), [DataSnapshot]())) {
    $0.0.append($1.key)
    $0.1.append( ($1 as? DataSnapshot)?.value )
}
let result = try FirebaseDecoder().decode([MyStruct].self, from: values)
for i in keys.indices {
    result[i].key = keys[i]
}
```
Or maybe:
```swift
let result = try snapshot.children
    .flatMap { ($0.key, try FirebaseDecoder().decode(MyStruct.self, from: ($0 as? DataSnapshot)?.value) ) }
    .map { $0.1.withKey($0.0) }
```
...If you added a `withKey(_ key: String) -> MyStruct` method.

**Comment by alickbass** [comment]
@tooolbox Anyway, as you see, there are already a lot of edge cases... That is why I don't think that such a utility function should be part of this library. You can define it yourself in your app. I am gonna close this issue, as I think it has already moved a slightly off 😉

**Comment by tooolbox** [comment]
@alickbass Good point, well thanks for your help 😄

**Comment by shaktiprakash099** [comment]
@alickbass  hey i am getting  like this error 

> typeMismatch(Swift.Array<Any>, Swift.DecodingError.Context(codingPath: [], debugDescription: "Not an array", underlyingError: nil))
