### ISSUE TITLE
how to match property with actual field name?

### ISSUE THREAD

**Issue by mickychen0524** [alickbass/CodableFirebase#27]
I can't find it in readme, can you help?

**Comment by mickychen0524** [comment]
and how to store in user default?

**Comment by alickbass** [comment]
Hi! Thanks for reaching out! The first question relates to the Codable itself. Please, take a look [here](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types), especially at the paragraph `Choose Properties to Encode and Decode Using Coding Keys`

**Comment by alickbass** [comment]
The second question I don't understand

**Comment by mickychen0524** [comment]
@alickbass I figured out, Thanks for your answer!
