### ISSUE TITLE
Unable to decode GeoPoint

### ISSUE THREAD

**Issue by hpbl** [alickbass/CodableFirebase#29]
Hi, the following code is failing:
```
        let model = try FirebaseDecoder().decode(
            FirestoreSpot.self,
            from: modelDict
        )
```

modelDict's decode is failing on the key `"location"`. The `location` property is of type GeoPoint, and as you can see bellow, modelDict has the correct type:

```
(lldb) po modelDict["location"]! is GeoPoint
true
```

the error I'm getting is that the value for this key is not a dictionary (which it shouldn't be):
```
(lldb) po error
▿ DecodingError
  ▿ typeMismatch : 2 elements
    - .0 : Swift.Dictionary<Swift.String, Any>
    ▿ .1 : Context
      ▿ codingPath : 1 element
        - 0 : SurfSpotter.FirestoreSpot.CodingKeys.location
      - debugDescription : "Not a dictionary"
      - underlyingError : nil
```

Can anyone help me? Am I missing something?

Thanks

**Comment by alickbass** [comment]
Hi! Thanks for reaching out! Please, try to use `FirebaseDecoder` instead. `GeoPoint` is only relevant to `Firestore`

**Comment by hpbl** [comment]
Yeah, sorry about that, I just realized this, and was about to post it myself. Thanks for the quick feedback and for the pod. 😊

**Comment by martindufort** [comment]
Hey @hpbl dod you resolve this issue ? Because you code is actually using a ```FirebaseDecoder```. Did you switch to ```FirestoreDecoder``` instead ?

**Comment by hpbl** [comment]
@martindufort Yes, switching to `FirestoreDecoder` fixes it

**Comment by hpbl** [comment]
@alickbass edit your comment so it reads "try to use `FirestoreDecoder` instead..."
