### ISSUE TITLE
Release for Swift 4.1

### ISSUE THREAD

**Issue by marcosgriselli** [alickbass/CodableFirebase#37]
After merging #33 there needs to be a new release `0.0.8`.

**Comment by alickbass** [comment]
Well, you need to update xcode project, project version number in info.plist and project version in podspec. Can you aubmit another pull request, please?

**Comment by alickbass** [comment]
I added you as a collaborator, so you are will be able to merge the PR and contribute to the full extend

**Comment by marcosgriselli** [comment]
Perfect, thanks!

**Comment by alickbass** [comment]
Done!
