### ISSUE TITLE
Generic Decode and Unbox [Enhancement]

### ISSUE THREAD

**Issue by serjooo** [alickbass/CodableFirebase#41]
Hey there,

First of all thank you for the great framework have done a really good job with this! 

I was going through the codebase and I noticed that you had to write each decode and unbox for each Type (UInt, UInt32, Int....). I was wondering if I would be able to write a more generic way of the unbox, and decode, and I was able with one complication however. The implementation would look something like this for the UInt family for example:

```
public func decode<T: UnsignedInteger>(_ key: Key, for type: T.Type) throws -> T {
        guard let entry = self.container[key.stringValue] else {
            throw DecodingError.keyNotFound(key, DecodingError.Context(codingPath: self.decoder.codingPath, debugDescription: "No value associated with key \(key) (\"\(key.stringValue)\")."))
        }
        
        self.decoder.codingPath.append(key)
        defer { self.decoder.codingPath.removeLast() }
        
        guard let value = try self.decoder.unbox(type, for: entry) else {
            throw DecodingError.valueNotFound(type, DecodingError.Context(codingPath: self.decoder.codingPath, debugDescription: "Expected \(type) value but found null instead."))
        }
        
        return value
}

func unbox<T: UnsignedInteger>(_ type: T.Type, for value: Any) throws -> T? {
        guard !(value is NSNull) else { return nil }
        
        guard let number = value as? NSNumber, number !== kCFBooleanTrue, number !== kCFBooleanFalse else {
            throw DecodingError._typeMismatch(at: self.codingPath, expectation: type, reality: value)
        }
        
        switch type {
        case is UInt.Type:
            return number.uintValue as? T
        case is UInt8.Type:
            return number.uint8Value as? T
        case is UInt16.Type:
            return number.uint16Value as? T
        case is UInt32.Type:
            return number.uint32Value as? T
        case is UInt64.Type:
            return number.uint64Value as? T
        default:
            throw DecodingError.dataCorrupted(DecodingError.Context(codingPath: self.codingPath, debugDescription: "Parsed JSON number <\(number)> does not fit in \(type)."))
        }
        
}
```

As you might have noticed, I have changed the parameters order from the original implementation. That's because for some reason the Compiler struggled to call the right function when calling unbox, or decode compared to the Generic Decodable. I'm guessing that's because all basic datatypes in Swift are maybe Codable as well?

However, I still think this might be a more elegant solution than the original, I'm not sure if its correct however, that is why opening the issue for discussion. Would love to hear your thoughts about this!

**Comment by serjooo** [comment]
@alickbass What do you think about implementing this?

**Comment by alickbass** [comment]
Hey! Sorry for such a late reply! I know there is a lot of code repetition, but that's exactly the code that is inside the JSONDecoder and JSONEncoder in the swift std. I just took that file and substituted where necessary with the dictionaries. TBH, I would prefer to keep it this way as in this way it would be okay to sync our file with the swift one's (for example for the snake case support) but I do see your point and I really appreciate you digging into the code!

**Comment by serjooo** [comment]
No worries! I see, didn't know that was the case. It makes most sense to keep it this way then. Will close this issue then. Thank you for giving your feedback!
