### ISSUE TITLE
Encode Document Reference So that It can be written in userdefaults as well

### ISSUE THREAD

**Issue by thesanjaythakkar** [alickbass/CodableFirebase#47]
Hi Support!

First of all thanks for a wonderful framework!

Actually, I was trying to encode DocumentReference as well but it shows me an error, Unsupported Type for UserDefaults DocumentReference.

Can you guys help me in this issue.

**Comment by alickbass** [comment]
Hi! Have you used the steps from [here](https://github.com/alickbass/CodableFirebase#how-to-use-geopoint-documentrefence-fieldvalue-timestamp-in-cloud-firestore) which encoder are you using?

**Comment by thesanjaythakkar** [comment]
Yes I also used extensions which are defined in that doc.

It encodes but it doesn't encode in the way it can save into UserDefaults.

**Comment by alickbass** [comment]
Well, there is no way to decode a Document Reference into JSON. You have use it's documentData and decode it turn.

**Comment by alickbass** [comment]
The document reference is something specific to Firebase. You should only use it with `FirestoreEncoder` that is why it gives you an error.

**Comment by thesanjaythakkar** [comment]
Yes agree, I have to use FirestoreEncoder, and it encode it, but I can't save the object which contains DocumentReference and encoded with FirestoreEncoder

**Comment by alickbass** [comment]
If you need to use it somewhere else, you need to avoid having `DocumentReference` in your model whatsoever and use something else. I hope this is helpful, but it is a limitation that you need to work with
