### ISSUE TITLE
iOS 12 with Swift 4.2 support

### ISSUE THREAD

**Issue by elalienx** [alickbass/CodableFirebase#53]
The new Xcode 10 ask to convert the code from Swift 4.1 to Swift 4.2.

**Comment by alickbass** [comment]
Thanks for reporting it! Would you like to submit a PR?

**Comment by serjooo** [comment]
@alickbass I wouldn’t mind doing this as well over the weekend 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alickbass** [comment]
I would be great to do it in a separate PR 😉
