### ISSUE TITLE
Handling nil values

### ISSUE THREAD

**Issue by mikesaltsman** [alickbass/CodableFirebase#55]
I'm having an issue where if the firestore object that is returned doesn't have values for fields in the class and it is handed to the decoder it breaks on the nil value. What is the proper way to deal with this such that it doesn't fault?  Is it something I'm not doing correctly, or is it just a limitation/issue within CodableFirebase? 

Here is the error I'm getting due to the field "shippingFee" not being in firestore: 

> Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.keyNotFound(CodingKeys(stringValue: "shippingFee", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"shippingFee\", intValue: nil) (\"shippingFee\").", underlyingError: nil))

What is recommended to work around this? 

Thank you!

**Comment by alickbass** [comment]
If you have a nil value, you need make sure that the type of that value in your code is `Optional<T>`. it's hard to say anything more without taking a look at the code itself

**Comment by mikesaltsman** [comment]
Making the value optional did the trick. Thank you!
