### ISSUE TITLE
Timestamp Handling

### ISSUE THREAD

**Issue by yangricardo** [alickbass/CodableFirebase#57]
Hi am having this issue with CodableFirebase decoding
I have some Codable fields that represents Dates, already tried Date Swift and Firebase Timestamp, used the `extension Timestamp: TimestampType {}` in my code and still receiving this error:

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Swift.DecodingError.typeMismatch(Swift.Double, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "dataNascimento", intValue: nil)], debugDescription: "Expected to decode Double but found FIRTimestamp instead.", underlyingError: nil))

At some point of time this fields needs to be `nil`, and it works, but only when i fetch data from Firestore after update this field i get this error.

![Uploading Captura de Tela 2018-10-28 às 15.39.35.png…]()

**Comment by alickbass** [comment]
Hi! Thanks for posting your question! Could you please share the code with your struct that conforms to `Codable`?

**Comment by alickbass** [comment]
You are using FirebaseDecoder, you need to use FirestoreDecoder and Encoder instead

**Comment by yangricardo** [comment]
Can't believe it hahaha
Thanks, too similar names!

**Comment by Demircivi** [comment]
Funny but I've encountered same issue after 2 years. Hahaha
