### ISSUE TITLE
Add Database support

### ISSUE THREAD

**Issue by alickbass** [alickbass/CodableFirebase#6]
Now the library supports only [Firestore](https://firebase.google.com/products/firestore/) and it is only in beta. However, the main is [Realtime Database](https://firebase.google.com/products/realtime-database/). We could reuse the policy for the `Date` and `Data` types that is used for the `JSONEncoder`. However, arrays are not supported with Firebase, so we need to throw an error.

**Comment by alickbass** [comment]
To make things even weirder, Realtime Database supports `NSArray`... However, I am not sure how it actually encodes it... need more investigation

**Comment by alickbass** [comment]
So array can be encoded with Database. The only difference between FireStore and Firebase now is the Date type

**Comment by Sroka** [comment]
Yes, please, I am so tired of doing this manually :)
