### ISSUE TITLE
Encoding Timestamp

### ISSUE THREAD

**Issue by zzzkk** [alickbass/CodableFirebase#65]
I have objects with `Timestamp` property and I want to add them to Firebase keeping timestamp as field of type `timestamp`. For now it is saved as a `number`. Is there any solution for this or I am doing something wrong?

**Comment by zzzkk** [comment]
I was using `FirebaseEncoder` instead of `FirestorEncoder` 😅

**Comment by abesmon** [comment]
That resolution made my night
