### ISSUE TITLE
Issue with extension - Document Reference, GeoPoint, ...

### ISSUE THREAD

**Issue by asher636** [alickbass/CodableFirebase#69]
Hi, I want to report an issue. Please have a look at the screenshot below. I have tried everything, cleaning, building etc but the issue remains. Can you tell what can be the problem or any solution in this regard. Thanks! 

<img width="1070" alt="screenshot 2019-02-25 at 12 28 31" src="https://user-images.githubusercontent.com/17403246/53321046-304ee600-38f9-11e9-9e71-04a2494c1dfa.png">

**Comment by serjooo** [comment]
You need to import Firebase/Firestore so that the compiler knows what those types are

**Comment by serjooo** [comment]
@asher636 Is your problem resolved? If so please do close this issue. Thank you!

**Comment by asher636** [comment]
Yep, it is done! Many thanks.
