### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by alickbass** [alickbass/CodableFirebase#7]
Firebase is cocoapods only, so cocoapods support for this library kinda makes sense :)

**Comment by MattTimmons** [comment]
would you mind checking on this? I am showing this in pod install..
`[!] Unable to find a specification for `CodableFirebase``

Happy new year!

**Comment by alickbass** [comment]
Hey @MattTimmons! I have just tested running pod install and it's working... Maybe you could try to use `pod update`?

**Comment by MattTimmons** [comment]
odd. yes. sorry running pod update resolved the issue.

**Comment by alickbass** [comment]
@MattTimmons great that you were able to get rid of the issue! Don't forget to start the repo 😉

**Comment by MattTimmons** [comment]
done. Thanks this repro saved me a ton of time!
