### ISSUE TITLE
Conversion to Swift 4.2 is available 

### ISSUE THREAD

**Issue by pepejeria** [alickbass/CodableFirebase#70]
I see in the projects podspec that the Swift version has been set t o 4.2. But I still get a "Conversion to Swift 4.2 is available" for this library. I see that Swift 4 has been set to the Swift Language Version in Build Settings. Is this an issue on your side?

**Comment by MatanGold** [comment]
Same here...?
Any idea why code doesn't fit Swift 4.2?
