### ISSUE TITLE
How to install as Swift Package

### ISSUE THREAD

**Issue by Wildchild9** [alickbass/CodableFirebase#88]
I tried to use this as a Swift Package and ran into the following error:
<img width="717" alt="Screen Shot 2020-03-15 at 11 19 44 PM" src="https://user-images.githubusercontent.com/35314567/76720573-90d2e000-6713-11ea-81da-6ea7236b637d.png">
<img width="724" alt="Screen Shot 2020-03-15 at 11 19 54 PM" src="https://user-images.githubusercontent.com/35314567/76720578-93cdd080-6713-11ea-882b-30848000f2da.png">

**Comment by leolelego** [comment]
Same here

**Comment by joakin8** [comment]
Another one here

**Comment by serjooo** [comment]
I have a PR open to get this fixed. Just waiting for it to get reviewed
